name: Run Daily Actions

on:
  schedule:
    - cron: '0 9 * * *' # every day 1 a.m. (UTC time 01:00, Beijing time 09:00)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install curl_cffi

      # - name: Setup Git
      #   run: |
      #     git config --local user.name "github-actions[bot]"
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run V2EX checkin script
        continue-on-error: true
        env:
          V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -m v2ex.v2ex

      - name: Run Nodeseek checkin script
        continue-on-error: true
        env:
          NODESEEK_COOKIE: ${{ secrets.NODESEEK_COOKIE }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -m nodeseek.nodeseek
      
      # - name: Commit and push
      #   run: |
      #     git add .
      #     git commit -m "Successfully run $(date +"%Y-%m-%d %H:%M:%S")"
      #     git push 